### ISSUE TITLE
Attempted to update a stale object on purchases list page

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1117]
An ActiveRecord::StaleObjectError occurred in purchases#list:

  Attempted to update a stale object: Preference
  app/models/preference.rb:208:in `set!'

**Comment by igkyab** [comment]
It throw when multiple users access to the same record (here the preferences).

In the code, the preferences has a reload before the save! method.

We will think about a solution in the future for this problem which is reproduced only on the demo.

**Comment by igkyab** [comment]
Error happened again today with the error message : 

An ActiveRecord::StaleObjectError occurred in purchases#list:

  Attempted to update a stale object: Preference
  app/models/preference.rb:219:in `set!'
