### ISSUE TITLE
interventions#compute (NoMethodError) "undefined method `variant' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1292]
A NoMethodError occurred in interventions#compute:

  undefined method `variant' for nil:NilClass
  lib/procedo/engine/interpreter.rb:124:in `run'

**Comment by igkyab** [comment]
New error message today : 

## Error
A NoMethodError occurred in interventions#compute:

  undefined method `variant' for nil:NilClass
  lib/procedo/engine/interpreter.rb:138:in `run'
