### ISSUE TITLE
interventions#create (ActiveRecord::AssociationTypeMismatch) "ProductGroup(#70220133926940) expected, got Bu...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1344]
v 2.19.0

An ActiveRecord::AssociationTypeMismatch occurred in interventions#create:

  ProductGroup(#70220133926940) expected, got BuildingDivision(#70220203567200)
  app/models/intervention.rb:278:in `block (2 levels) in <class:Intervention>'

  * Parameters : {"updater"=>"/backend/interventions/compute.json", "intervention"=>{"procedure_name"=>"animal_group_changing", "nature"=>"record", "state"=>"done", "issue_id"=>"", "request_intervention_id"=>"", "description"=>"", "actions"=>["animal_group_changing"], "trouble_encountered"=>"0", "trouble_description"=>"", "prescription_id"=>"", "working_periods_attributes"=>{"0"=>{"_destroy"=>"false", "started_at"=>"2016-11-16 10:16", "stopped_at"=>"2016-11-16 11:16"}}, "targets_attributes"=>{"0"=>{"_destroy"=>"false", "reference_name"=>"animal", "product_id"=>"281", "new_container_id"=>"", "new_group_id"=>"37", "new_variant_id"=>""}, "1"=>{"_destroy"=>"false", "reference_name"=>"animal", "product_id"=>"289", "new_container_id"=>"", "new_group_id"=>"37", "new_variant_id"=>""}, "2"=>{"_destroy"=>"false", "reference_name"=>"animal", "product_id"=>"785", "new_container_id"=>"", "new_group_id"=>"37", "new_variant_id"=>""}}}, "dialog"=>"dialog-2", "controller"=>"backend/interventions", "action"=>"create"}

**Comment by igkyab** [comment]
Same error today on other line : 

## Error
An ActiveRecord::AssociationTypeMismatch occurred in interventions#create:

  ProductGroup(#70335256569740) expected, got BuildingDivision(#70335226864640)
  app/models/intervention.rb:284:in `block (2 levels) in <class:Intervention>'

---
## Environment
- **Version :** 2.36.1
- **Date :** 23/02/2017
- **Server :** production
