### ISSUE TITLE
purchases#invoice (ActiveRecord::RecordInvalid) "Validations échouées : Nom a déjà été pris"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1388]
## Error
An ActiveRecord::RecordInvalid occurred in purchases#invoice:

  Validations échouées : Nom a déjà été pris
  app/models/journal.rb:169:in `used_for_unbilled_payables!'

---
## Environment
- **Version :** 2.20.1
- **Server :** production

**Comment by igkyab** [comment]
Same error today on other line : 

## Error
An ActiveRecord::RecordInvalid occurred in purchases#invoice:

  Validations échouées : Nom a déjà été pris
  app/models/purchase_item.rb:215:in `update_fixed_asset'
