### ISSUE TITLE
deposits#show (RuntimeError) "net.sf.jasperreports.engine.JRException: java.io.FileNotFoundException: /var/w...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1426]
## Error
A RuntimeError occurred in deposits#show:

  net.sf.jasperreports.engine.JRException: java.io.FileNotFoundException: /var/www/sheep-prod/releases/20161201170322-ekylibre-2.21.6/private/demo/reporting/5/content.xml.jasper
  config/initializers/apartment.rb:52:in `call'

---
## Environment
- **Version:** 2.21.6
- **Server :** production

**Comment by igkyab** [comment]
Same error for exports#show : 

## Error

A RuntimeError occurred in exports#show:
  net.sf.jasperreports.engine.JRException: java.io.FileNotFoundException: /var/www/sheep-prod/releases/20161201170322-ekylibre-2.21.6/private/demo/reporting/22/content.xml.jasper
  config/initializers/apartment.rb:52:in `call'
