### ISSUE TITLE
sales#invoice (NoMethodError) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1446]
## Error
A NoMethodError occurred in sales#invoice:

  undefined method `id' for nil:NilClass
  app/models/journal_entry.rb:375:in `add!'

---
## Environment
- **Version :** 2.22.2
- **Server :** production

**Comment by igkyab** [comment]
Changed stacktrace : 

A NoMethodError occurred in sales#invoice:

  undefined method `id' for nil:NilClass
  app/models/journal_entry_item.rb:248:in `attributes_for'
