### ISSUE TITLE
parcels#invoice (ActiveRecord::RecordInvalid) "Validations échouées : Né(e) le doit être le ou avant le 08/1...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1465]
## Error
An ActiveRecord::RecordInvalid occurred in parcels#invoice:

  Validations échouées : Né(e) le doit être le ou avant le 08/12/2016 13:15
  app/models/parcel.rb:509:in `block (3 levels) in convert_to_purchase'

---
## Environment
- **Version :** 2.24.0
- **Server :** production

**Comment by igkyab** [comment]
Same error today on other line

## Error
An ActiveRecord::RecordInvalid occurred in parcels#invoice:

  Validations échouées : Né(e) le doit être le ou avant le 08/12/2016 13:15
  app/models/parcel.rb:523:in `block (3 levels) in convert_to_purchase'
