### ISSUE TITLE
interventions#compute (RuntimeError) "Cannot divide by zero: (VALUE * sum_working_zone_areas(plant, :hectare...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1506]
## Error

A RuntimeError occurred in interventions#compute:

  Cannot divide by zero: (VALUE * sum_working_zone_areas(plant, :hectare)) / VARIANT.net_mass(quintal) (0.0 / 0.0)
  lib/procedo/engine/interpreter.rb:50:in `run'

---
## Environment
- **Version :** 2.26.0
- **Server :** production

**Comment by igkyab** [comment]
Same error today : 

A RuntimeError occurred in interventions#compute:

  Cannot divide by zero: (VALUE * sum_working_zone_areas(cultivation, :hectare)) / PRODUCT..net_mass(ton) (1532.693647730979 / 0.0)
  lib/procedo/engine/interpreter.rb:50:in `run'
