### ISSUE TITLE
intervention_participations#index (ActionView::Template::Error) "undefined method `read_at' for nil:NilClass...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1575]
## Error
An ActionView::Template::Error occurred in intervention_participations#index:

  undefined method `read_at' for nil:NilClass
  app/models/intervention_participation.rb:202:in `unconverted_crumbs'

---
## Environment
- **Version :** 2.30.2
- **Server :** production

**Comment by igkyab** [comment]
I have this error today : 

An ActionView::Template::Error occurred in intervention_participations#index:

  undefined method `read_at' for nil:NilClass
  app/models/intervention_participation.rb:202:in `unconverted_crumbs'
