### ISSUE TITLE
intervention_participations#create (ActiveRecord::RecordInvalid) "Validations échouées : Produit ne peut pas...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1587]
## Error
An ActiveRecord::RecordInvalid occurred in intervention_participations#create:

  Validations échouées : Produit ne peut pas être vide
  app/controllers/api/v1/intervention_participations_controller.rb:35:in `create'

---
## Environment
- **Version :** 2.30.2
- **Server :** production

**Comment by igkyab** [comment]
New error today : 

An ActiveRecord::RecordInvalid occurred in intervention_participations#create:

  Validations échouées : Produit ne peut pas être vide
  app/controllers/api/v1/intervention_participations_controller.rb:37:in `create'
