### ISSUE TITLE
parcels#invoice (ActiveRecord::RecordInvalid) "Validations échouées : L'écriture ne peut être enregistrée lo...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1647]
## Error
An ActiveRecord::RecordInvalid occurred in parcels#invoice:

  Validations échouées : L'écriture ne peut être enregistrée lors d'un échange d'exercice comptable.
  app/models/journal_entry.rb:339:in `block in cancel'

---
## Environment
- **Version :** 2.34.0
- **Server :** production

**Comment by igkyab** [comment]
Different stack trace today : 

An ActiveRecord::RecordInvalid occurred in parcels#invoice:

  Validations échouées : L'écriture ne peut être enregistrée lors d'un échange d'exercice comptable.
  app/models/journal_entry.rb:371:in `block in cancel'
