### ISSUE TITLE
cashes#index (I18n::InvalidPluralizationData) "translation data {:one=>\"Es gibt einen Eintrag hinzuweisen\"...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1656]
## Error
An I18n::InvalidPluralizationData occurred in cashes#index:

  translation data {:one=>"Es gibt einen Eintrag hinzuweisen"} can not be used with :count => 681
  app/controllers/application_controller.rb:110:in `notify'

---
## Environment
- **Version :** 2.34.1
- **Server :** production

**Comment by igkyab** [comment]
Same error today : 

## Error
An I18n::InvalidPluralizationData occurred in cashes#index:

  translation data {:one=>"Hay una entrada para señalar"} can not be used with :count => 712
  app/controllers/application_controller.rb:110:in `notify'

---
## Environment
- **Version :** 2.34.2
- **Server :** production
