### ISSUE TITLE
RecordNotFound when i click on new regularization

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1670]
## Error
ActiveRecord::RecordNotFound (Couldn't find Journal):
  app/controllers/backend/journal_entries_controller.rb:70:in `new'
  config/initializers/apartment.rb:52:in `call'

---
## Environment
- **Version :** 2.34.2
- **Server :** production

**Comment by igkyab** [comment]
Fixed by e0e7fe151105688dc58bf05a9ecc5c74b68d15d4
