### ISSUE TITLE
entities#show (ActionView::Template::Error) "translation data {:one=>\"1 evento\"} can not be used with :cou...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1678]
## Error
An ActionView::Template::Error occurred in entities#show:

  translation data {:one=>"1 evento"} can not be used with :count => 0
  config/initializers/10-patches.rb:34:in `tl'

---
## Environment
- **Version :** 2.34.3
- **Server :** production

**Comment by igkyab** [comment]
Error come back today

## Error
An ActionView::Template::Error occurred in entities#show:

  translation data {:one=>"1 tema"} can not be used with :count => 0
  config/initializers/10-patches.rb:34:in `tl'

---
## Environment
- **Version :** 2.36.4
- **Server :** production
- **Date :** 09/03/2017
