### ISSUE TITLE
RuntimeError: Unknown equipment: vendor=, model=

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1919]
Error located in a job SensorReading
```
RuntimeError: Unknown equipment: vendor=, model=
  from app/models/sensor.rb:98:in `retrieve'
  from app/models/sensor.rb:153:in `block in retrieve_all'
  from active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
  from active_record/relation/batches.rb:51:in `each'
  from active_record/relation/batches.rb:51:in `block in find_each'
  from active_record/relation/batches.rb:124:in `find_in_batches'
  from active_record/relation/batches.rb:50:in `find_each'
  from app/models/sensor.rb:152:in `retrieve_all'
  from app/jobs/sensors_reading_job.rb:5:in `perform'
  from active_job/execution.rb:32:in `block in perform_now'
```
### How to reproduce

**Comment by burisu** [comment]
https://sentry.io/ekylibre/ekylibre/issues/289892303/
