### ISSUE TITLE
Missing interpolation argument :container_name requested from product unroll translation ("%{work_number} %{name} (%{number}) - %{contain...)

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1949]
```
I18n::MissingInterpolationArgument: missing interpolation argument :container_name in "%{work_number} %{name} (%{number}) - %{container_name}" ({:id=>17, :type=>"BuildingDivision", :name=>"Taupinière", :number=>"P00000000017", :variant_id=>76, :nature_id=>45, :category_id=>35, :initial_born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :initial_dead_at=>nil, :initial_container_id=>5, :initial_owner_id=>1, :initial_enjoyer_id=>nil, :initial_population=>#<BigDecimal:56517b4295c8,'0.0',9(18)>, :initial_father_id=>nil, :initial_mother_id=>nil, :variety=>"building_division", :derivative_of=>nil, :tracking_id=>nil, :fixed_asset_id=>nil, :born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :dead_at=>nil, :description=>nil, :picture_file_name=>nil, :picture_content_type=>nil, :picture_file_size=>nil, :picture_updated_at=>nil, :identification_number=>nil, :work_number=>"S04_D01", :address_id=>nil, :parent_id=>nil, :default_storage_id=>5, :created_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :updated_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :creator_id=>nil, :updater_id=>nil, :lock_version=>0, :initial_shape=>nil, :person_id=>nil, :initial_geolocation=>nil, :uuid=>"a240d553-f2da-420a-b54a-875ac9035b4a", :initial_movement_id=>17, :custom_fields=>nil, :team_id=>nil, :member_variant_id=>nil, :birth_date_completeness=>nil, :birth_farm_number=>nil, :country=>nil, :filiation_status=>nil, :first_calving_on=>nil, :mother_country=>nil, :mother_variety=>nil, :mother_identification_number=>nil, :father_country=>nil, :father_variety=>nil, :father_identification_number=>nil, :origin_country=>nil, :origin_identification_number=>nil, :end_of_life_reason=>nil, :originator_id=>nil, :population=>#<BigDecimal:5651868284c0,'0.1E1',9(18)>, :unit_name=>"Salle"} given)
  app/models/product.rb:439:in `unroll_name'
    'unrolls.backend/products'.t(attributes.symbolize_keys.merge(population: population, unit_name: unit_name))
  app/views/backend/cells/stock_container_map_cells/show.html.haml:20:in `block in _app_views_backend_cells_stock_container_map_cells_show_html_haml__616423485665580636_47454313767060'
    item = {
  app/views/backend/cells/stock_container_map_cells/show.html.haml:5:in `_app_views_backend_cells_stock_container_map_cells_show_html_haml__616423485665580636_47454313767060'
    # FIXME Find a better way to find storage
  config/initializers/apartment.rb:72:in `call'
    super
...
(151 additional frame(s) were not displayed)

ActionView::Template::Error: missing interpolation argument :container_name in "%{work_number} %{name} (%{number}) - %{container_name}" ({:id=>17, :type=>"BuildingDivision", :name=>"Taupinière", :number=>"P00000000017", :variant_id=>76, :nature_id=>45, :category_id=>35, :initial_born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :initial_dead_at=>nil, :initial_container_id=>5, :initial_owner_id=>1, :initial_enjoyer_id=>nil, :initial_population=>#<BigDecimal:56517b4295c8,'0.0',9(18)>, :initial_father_id=>nil, :initial_mother_id=>nil, :variety=>"building_division", :derivative_of=>nil, :tracking_id=>nil, :fixed_asset_id=>nil, :born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :dead_at=>nil, :description=>nil, :picture_file_name=>nil, :picture_content_type=>nil, :picture_file_size=>nil, :picture_updated_at=>nil, :identification_number=>nil, :work_number=>"S04_D01", :address_id=>nil, :parent_id=>nil, :default_storage_id=>5, :created_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :updated_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :creator_id=>nil, :updater_id=>nil, :lock_version=>0, :initial_shape=>nil, :person_id=>nil, :initial_geolocation=>nil, :uuid=>"a240d553-f2da-420a-b54a-875ac9035b4a", :initial_movement_id=>17, :custom_fields=>nil, :team_id=>nil, :member_variant_id=>nil, :birth_date_completeness=>nil, :birth_farm_number=>nil, :country=>nil, :filiation_status=>nil, :first_calving_on=>nil, :mother_country=>nil, :mother_variety=>nil, :mother_identification_number=>nil, :father_country=>nil, :father_variety=>nil, :father_identification_number=>nil, :origin_country=>nil, :origin_identification_number=>nil, :end_of_life_reason=>nil, :originator_id=>nil, :population=>#<BigDecimal:5651868284c0,'0.1E1',9(18)>, :unit_name=>"Salle"} given)

ActionView::Template::Error: missing interpolation argument :container_name in "%{work_number} %{name} (%{number}) - %{container_name}" ({:id=>17, :type=>"BuildingDivision", :name=>"Taupinière", :number=>"P00000000017", :variant_id=>76, :nature_id=>45, :category_id=>35, :initial_born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :initial_dead_at=>nil, :initial_container_id=>5, :initial_owner_id=>1, :initial_enjoyer_id=>nil, :initial_population=>#<BigDecimal:56517b4295c8,'0.0',9(18)>, :initial_father_id=>nil, :initial_mother_id=>nil, :variety=>"building_division", :derivative_of=>nil, :tracking_id=>nil, :fixed_asset_id=>nil, :born_at=>Sun, 01 Jan 1995 11:00:00 CET +01:00, :dead_at=>nil, :description=>nil, :picture_file_name=>nil, :picture_content_type=>nil, :picture_file_size=>nil, :picture_updated_at=>nil, :identification_number=>nil, :work_number=>"S04_D01", :address_id=>nil, :parent_id=>nil, :default_storage_id=>5, :created_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :updated_at=>Mon, 20 Feb 2017 23:06:24 CET +01:00, :creator_id=>nil, :updater_id=>nil, :lock_version=>0, :initial_shape=>nil, :person_id=>nil, :initial_geolocation=>nil, :uuid=>"a240d553-f2da-420a-b54a-875ac9035b4a", :initial_movement_id=>17, :custom_fields=>nil, :team_id=>nil, :member_variant_id=>nil, :birth_date_completeness=>nil, :birth_farm_number=>nil, :country=>nil, :filiation_status=>nil, :first_calving_on=>nil, :mother_country=>nil, :mother_variety=>nil, :mother_identification_number=>nil, :father_country=>nil, :father_variety=>nil, :father_identification_number=>nil, :origin_country=>nil, :origin_identification_number=>nil, :end_of_life_reason=>nil, :originator_id=>nil, :population=>#<BigDecimal:5651868284c0,'0.1E1',9(18)>, :unit_name=>"Salle"} given)
```

**Comment by burisu** [comment]
No news? I close
