### ISSUE TITLE
Invalid reflection :purchase_payments for SaleOpportunity

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#1950]
```
ArgumentError: Invalid reflection :purchase_payments for SaleOpportunity
  app/helpers/backend/timeline_helper.rb:163:in `side'
    raise ArgumentError, "Invalid reflection #{name.inspect} for #{@model.name}"
  app/views/backend/sale_opportunities/show.html.haml:45:in `block (3 levels) in _app_views_backend_sale_opportunities_show_html_haml___1265968831384752717_47454307511800'
    - l.side :purchase_payments, new: false
  app/helpers/backend/timeline_helper.rb:183:in `timeline'
    yield line
  app/views/backend/sale_opportunities/show.html.haml:39:in `block (2 levels) in _app_views_backend_sale_opportunities_show_html_haml___1265968831384752717_47454307511800'
    = timeline(resource) do |l|
  app/helpers/backend/base_helper.rb:349:in `block in janus'
    content_tag(:div, id: "face-#{face_name}", data: { face: face_name }, class: classes, &face.block)
...
(151 additional frame(s) were not displayed)

ActionView::Template::Error: Invalid reflection :purchase_payments for SaleOpportunity

ActionView::Template::Error: Invalid reflection :purchase_payments for SaleOpportunity
```

**Comment by burisu** [comment]
No news? I close
