### ISSUE TITLE
Timeline don't work with models without controllers like product_ownerships

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#350]
An ActionController::UrlGenerationError occurred in matters#show:
```
  No route matches {:action=>"show", :controller=>"backend/product_ownerships", :id=>238}
  app/helpers/application_helper.rb:179:in `link_to'
```

Backtrace:
```
  app/helpers/application_helper.rb:179:in `link_to'
  app/views/backend/shared/_timeline.html.haml:15:in `block in _app_views_backend_shared__timeline_html_haml___2087842885919046075_70018532736280'
  app/views/backend/shared/_timeline.html.haml:12:in `each'
  app/views/backend/shared/_timeline.html.haml:12:in `_app_views_backend_shared__timeline_html_haml___2087842885919046075_70018532736280'
  app/helpers/backend/timeline_helper.rb:150:in `timeline'
  app/views/backend/products/_timeline.html.haml:1:in `_app_views_backend_products__timeline_html_haml__2118291418420812542_70018532476340'
  app/views/backend/matters/show.html.haml:69:in `block (3 levels) in _app_views_backend_matters_show_html_haml__1445226559467664772_70018511537320'
  app/helpers/backend/beehive_helper.rb:121:in `cell'
  app/views/backend/matters/show.html.haml:68:in `block (2 levels) in _app_views_backend_matters_show_html_haml__1445226559467664772_70018511537320'
  app/helpers/backend/beehive_helper.rb:182:in `[]'
  app/helpers/backend/beehive_helper.rb:182:in `box'
  app/helpers/backend/beehive_helper.rb:137:in `hbox'
  app/views/backend/matters/show.html.haml:48:in `block in _app_views_backend_matters_show_html_haml__1445226559467664772_70018511537320'
  app/helpers/backend/beehive_helper.rb:34:in `[]'
  app/helpers/backend/beehive_helper.rb:34:in `beehive'
  app/views/backend/matters/show.html.haml:6:in `_app_views_backend_matters_show_html_haml__1445226559467664772_70018511537320'
```

**Comment by burisu** [comment]
This bug cannot be reproduced in dev mode, maybe due to ruby difference between 2.1.3 and 2.0.0
