### ISSUE TITLE
Access error on archive consultation due to migration runner (root)

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#353]
An Errno::EACCES occurred in sales#show:

  Permission denied @ dir_s_mkdir - /var/www/sheep-demo/releases/20150308192415-ekylibre-1.1.0.rc1/private/demo/attachments/documents/000/000/023
  app/models/document_template.rb:216:in `document'

-------------------------------
Request:
-------------------------------

  * URL        : http://demo.ekylibre.farm/backend/sales/427.pdf?key=V201502000427&step=default&template=16
  * HTTP Method: GET
  * Parameters : {"key"=>"V201502000427", "step"=>"default", "template"=>"16", "controller"=>"backend/sales", "action"=>"show", "id"=>"427", "format"=>"pdf"}
  * Timestamp  : 2015-03-09 16:25:10 +0000
  * Server : ma001
  * Rails root : /var/www/sheep-demo/releases/20150308192415-ekylibre-1.1.0.rc1
  * Process: 6905

-------------------------------
Backtrace:
-------------------------------

  app/models/document_template.rb:216:in `document'
  app/models/document_template.rb:188:in `export'
  app/controllers/backend/base_controller.rb:42:in `respond_with_with_template'
  app/controllers/backend/sales_controller.rb:140:in `show'

**Comment by burisu** [comment]
Production problem only. The migration on Document/DocumentArchive merge moves files so, it's needed to check file rights after migrations
