### ISSUE TITLE
Crumbs#index fails on working_sets expression

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#471]
An ActionView::Template::Error occurred in crumbs#index:

    Expected one of " ", [a-z] at line 1, column 4 (byte 4) after is 
    Expression: "is :sortable"
    lib/working_set.rb:38:in `parse'

### Backtrace:
```
  lib/working_set.rb:38:in `parse'
  lib/working_set.rb:49:in `check_record'
  app/models/product_nature.rb:150:in `of_expression'
  app/models/product.rb:235:in `of_expression'
  lib/procedo/variable.rb:285:in `fulfilled_by?'
  lib/procedo/variable.rb:295:in `block in possible_matching_for'
  lib/procedo/variable.rb:294:in `each'
  lib/procedo/variable.rb:294:in `possible_matching_for'
  lib/procedo/procedure.rb:640:in `block in matching_variables_for'
  lib/procedo/procedure.rb:639:in `each'
  lib/procedo/procedure.rb:639:in `matching_variables_for'
  app/models/intervention.rb:423:in `block in match'
  app/models/intervention.rb:421:in `each'
  app/models/intervention.rb:421:in `map'
  app/models/intervention.rb:421:in `match'
  app/models/crumb.rb:235:in `possible_procedures_matching'
  app/models/crumb_set.rb:25:in `possible_procedures_matching'
  app/views/backend/crumbs/_intervention.html.haml:6:in `block (2 levels) in _app_views_backend_crumbs__intervention_html_haml___203535355152891568_69937964086480'
  app/views/backend/crumbs/_intervention.html.haml:5:in `block in _app_views_backend_crumbs__intervention_html_haml___203535355152891568_69937964086480'
  app/helpers/application_helper.rb:843:in `form_actions'
  app/views/backend/crumbs/_intervention.html.haml:1:in `_app_views_backend_crumbs__intervention_html_haml___203535355152891568_69937964086480'
  app/views/backend/crumbs/index.html.haml:59:in `block (3 levels) in _app_views_backend_crumbs_index_html_haml__2315753419933540693_69937952380180'
  app/helpers/cobbles_helper.rb:14:in `initialize'
  app/helpers/cobbles_helper.rb:39:in `new'
  app/helpers/cobbles_helper.rb:39:in `cobble'
  app/views/backend/crumbs/index.html.haml:58:in `block (2 levels) in _app_views_backend_crumbs_index_html_haml__2315753419933540693_69937952380180'
  app/views/backend/crumbs/index.html.haml:57:in `each'
  app/views/backend/crumbs/index.html.haml:57:in `block in _app_views_backend_crumbs_index_html_haml__2315753419933540693_69937952380180'
  app/helpers/cobbles_helper.rb:70:in `cobbles'
  app/views/backend/crumbs/index.html.haml:56:in `_app_views_backend_crumbs_index_html_haml__2315753419933540693_69937952380180'
```

**Comment by burisu** [comment]
The bug seems to come from use of raw variety parameter of procedures
