### ISSUE TITLE
Error when adding an animal farming production with a blank size_value

### ISSUE THREAD

**Issue by Nyxelio** [ekylibre/ekylibre#510]
![screenshot](https://cloud.githubusercontent.com/assets/9863590/13916066/9fe064d2-ef58-11e5-9153-d83a32ece5eb.png)

NoMethodError (undefined method `in' for nil:NilClass):
  app/models/activity_production.rb:178:in `block in <class:ActivityProduction>'
  config/initializers/10-patches.rb:200:in `around_validation'
  app/controllers/backend/base_controller.rb:93:in `block in save_and_redirect'
  app/controllers/backend/base_controller.rb:92:in `save_and_redirect'

**Comment by Nyxelio** [comment]
Fixed by b0024608062663b29bc3e705626d7aeb82fad30d
