### ISSUE TITLE
Loan creation fails when currencies in loan and journals are different

### ISSUE THREAD

**Issue by burisu** [ekylibre/ekylibre#520]
A RuntimeError occurred in loans#create:
```
  You create an entry where the absolute currency ("AED") is not the real ("EUR") or current one ("EUR")
  app/models/journal_entry.rb:190:in `block in <class:JournalEntry>'
```

**Backtrace:**
```
  app/models/journal_entry.rb:190:in `block in <class:JournalEntry>'
  config/initializers/10-patches.rb:200:in `around_validation'
  lib/ekylibre/record/bookkeep.rb:58:in `block in journal_entry'
  lib/ekylibre/record/bookkeep.rb:43:in `journal_entry'
  app/models/loan.rb:84:in `block in <class:Loan>'
  app/controllers/backend/base_controller.rb:93:in `block in save_and_redirect'
  app/controllers/backend/base_controller.rb:92:in `save_and_redirect'
```

**Comment by Aquaj** [comment]
Fixed by Hajimari update.
