### ISSUE TITLE
During intervention, the shape is missing when selecting a target

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#667]
![screenshot at 2016-05-24 09 35 00](https://cloud.githubusercontent.com/assets/1838491/15495882/f3a456fc-2192-11e6-95f1-4e258ec6db5b.png)

```cmd
NoMethodError (undefined method `each' for #<Procedo::Engine::Set:0x005609c73973b8>):
  lib/procedo/engine/functions.rb:53:in `merge_working_zones'
  lib/procedo/engine/interpreter.rb:69:in `run'
  lib/procedo/engine/interpreter.rb:19:in `interpret'
  lib/procedo/engine/interpreter.rb:5:in `interpret'
  lib/procedo/engine/intervention.rb:55:in `interpret'
  lib/procedo/engine/intervention/product_parameter.rb:160:in `compute_reading'
  lib/procedo/engine/intervention/product_parameter.rb:142:in `block (3 levels) in impact_on_parameters'
  lib/procedo/engine/intervention/product_parameter.rb:139:in `each'
  lib/procedo/engine/intervention/product_parameter.rb:139:in `block (2 levels) in impact_on_parameters'
  lib/procedo/engine/intervention/product_parameter.rb:119:in `each'
  lib/procedo/engine/intervention/product_parameter.rb:119:in `block in impact_on_parameters'
  lib/procedo/engine/intervention/product_parameter.rb:116:in `each'
  lib/procedo/engine/intervention/product_parameter.rb:116:in `impact_on_parameters'
  lib/procedo/engine/intervention/product_parameter.rb:78:in `impact_dependencies!'
  lib/procedo/engine/intervention/product_parameter.rb:42:in `working_zone='
  lib/procedo/engine/intervention/product_parameter.rb:94:in `block in impact_on_attributes'
  lib/procedo/engine/intervention/product_parameter.rb:83:in `each'
  lib/procedo/engine/intervention/product_parameter.rb:83:in `impact_on_attributes'
  lib/procedo/engine/intervention/product_parameter.rb:76:in `impact_dependencies!'
  lib/procedo/engine/intervention/product_parameter.rb:37:in `product_id='
  lib/procedo/engine/intervention/parameter.rb:48:in `impact'
  lib/procedo/engine/intervention/product_parameter.rb:71:in `impact_with'
  lib/procedo/engine/intervention/group_parameter.rb:84:in `impact_with'
  lib/procedo/engine/intervention/group_parameter.rb:84:in `impact_with'
  lib/procedo/engine/intervention.rb:78:in `impact_with'
  lib/procedo/engine/intervention.rb:69:in `impact_with!'
  app/controllers/backend/interventions_controller.rb:135:in `compute'
```

**Comment by burisu** [comment]
Fixed by 0747e8ac203259ecd05ca6b26c78f03df49d32cb
